version: '3.8'

services:
  # Qdrant Vector DB Service
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    ports:
      - "7000:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Neo4j Graph DB Service
  neo4j:
    image: neo4j:5.17.0
    container_name: neo4j_service
    ports:
      - "7001:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Redis Caching Service
  redis:
    image: redis:7.2-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Elasticsearch Logging Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "7002:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Filebeat Lightweight Log Shipper Service
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.3
    container_name: filebeat
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      # --- THIS IS THE ONLY LINE TO CHANGE (remove ":ro") ---
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      # --- KEEP ":ro" ON THIS LINE ---
      - ./server/logs:/usr/share/filebeat/logs:ro
    command: sh -c 'chmod go-w /usr/share/filebeat/filebeat.yml && filebeat -e -d "publish"'
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Kibana Visualization Service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    ports:
      - "7003:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Prometheus Monitoring Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "7004:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - ai_tutor_network
    restart: unless-stopped

  # Grafana Visualization Service
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "7005:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # --- ADD THIS ENTIRE SECTION ---
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      # --- END OF ADDED SECTION ---
    depends_on:
      - prometheus
    networks:
      - ai_tutor_network
    restart: unless-stopped


volumes:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  redis_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data:

networks:
  ai_tutor_network:
    driver: bridge