# prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodejs_backend'
    # Use the container name and port defined in docker-compose.yml
    static_configs:
      - targets: ['nodejs_backend:5001']

  - job_name: 'python_rag_service'
    # Use the container name and port for the python service
    static_configs:
      - targets: ['python_rag_service:5000']