version: "3.8"

services:
  # Qdrant Service Definition
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # Neo4j Service Definition
  neo4j:
    image: neo4j:5.17.0
    container_name: neo4j_service
    ports:
      - "7474:7474"
      - "8768:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: unless-stopped

  # Redis Service Definition
  redis:
    image: redis:7.2-alpine # Lightweight and stable version of Redis
    container_name: redis_service
    ports:
      - "6379:6379" # Default Redis port
    volumes:
      - redis_data:/data # Optional: Persistent storage for Redis data
    restart: unless-stopped

volumes:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  redis_data: # Added named volume for Redis persistence
